const backend='http://localhost:5400'

const summaryApi={
   signUp:{
    url:`${backend}/api/signup`,
    method:'post'
   },
   login:{
      url:`${backend}/api/login`,
      method:'post'
   },
   userDetails:{
      url:`${backend}/api/user-details`,
      method:'get'
   },
   logout:{
       url:`${backend}/api/user-logout`,
       method:'get'
   },
   allusers:{
     url:`${backend}/api/all-users`,
     method:'get'
   },
   updateUser:{
    url:`${backend}/api/update-user`,
    method:'post'
   }, 
   uploadProduct:{
     url:`${backend}/api/upload-product`,
     method:'post'
   },
   getallProducts:{
     url:`${backend}/api/getall-products`,
     method:'get'
   },
   editProduct:{
    url:`${backend}/api/edit-product`,
    method:'post'
   },
   getAllCategories:{
     url:`${backend}/api/get-allCategories`,
     method:'get'
   },
   getSingleCategory:{
    url:`${backend}/api/fetch-category`,
    method:'post'
   },
   getProductDetails:{
    url:`${backend}/api/product-details`,
    method:'post'
   },
   
    cartDetails:{
     url:`${backend}/api/addToCart`,
     method:'post'
     },
     
     countCart:{
      url:`${backend}/api/countCart`,
      method:'get'
     },
     cartByUserId:{
      url:`${backend}/api/cartByUser`,
      method:'get'
     },
     UpdatingCartQuantityByUserId:{
        url:`${backend}/api/updateCartByUser`,
        method:'post'
     },
    DeleteCartItemsByUserId:{
      url:`${backend}/api/deleteCartByUser`,
      method:'post'
    },
    SearchProduct:{
      url:`${backend}/api/searchProduct`,
      method:'get'
    },
    MutlitpleCategoryByUserId:{
     url:`${backend}/api/fetch-MultipleCategory`,
     method:'post'
    },
    Sorting:{
      url:`${backend}/api/sort`,
      method:'post'
    },
    Payment:{
      url:`${backend}/api/checkout`,
      method:'post'
    },
    Order:{
      url:`${backend}/api/order`,
      method:'get'
    },
    AdminOrders:{
      url:`${backend}/api/All-orders`,
      method:'get'
    },
    ForgotPassword:{
      url:`${backend}/api/forgot-password`,
      method:'post'
    }
   
}
export default summaryApi